"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-io' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex",
    "scitex_dev",
    "scitex_dev._cli._completion",
    "scitex_dev.cli",
    "scitex_dev.linter._rules._base",
    "scitex_dev.linter.checker",
    "scitex_logging",
    "scitex_stats._utils._normalizers",
    "scitex_stats._dataclasses",
    "scitex_stats.io",
    "scitex.io.bundle",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_resolves_to_module(module_name):
    """Importing scitex-io's declared cross-package dependency must succeed."""
    # Arrange
    # (importorskip skips when peer standalone absent; otherwise asserts
    # the imported object is the named module.)
    # Act
    mod = pytest.importorskip(module_name)
    # Assert
    assert getattr(mod, "__name__", None) == module_name
